# Introduction to Neural Networks: The Perceptron and Foundations

This document captures the foundational building blocks of deep learning, starting from a single artificial neuron and advancing through mathematical modeling, logic gates, activation functions, structural limitations, and data flow paradigms.

--- 
## 1. The Building Block: The Perceptron

To build a truly profound understanding of neural networks, we start exactly where the field began: with a single artificial neuron. This foundational building block is called the **Perceptron**.

Conceptually, a perceptron is a decision-making machine. It takes several binary inputs, weighs their relative importance, and produces a single output.

### The Architecture of a Perceptron
Imagine you are trying to decide whether to go to a music festival today. Your decision depends on three factors (inputs):
* Is the weather good? ($x_1$)
* Is your friend going with you? ($x_2$)
* Is the festival near public transit? ($x_3$)

In a perceptron, these inputs are represented as $x_1, x_2, x_3$. However, not all factors matter to you equally. If you hate the rain, bad weather is a dealbreaker, but you might not care much about public transit. 

This is where **weights** ($w_1, w_2, w_3$) come in. Weights express the relative importance of each input.

### The Mathematical Formulation
The perceptron multiplies each input by its corresponding weight and adds them all together. This is called the **weighted sum**:

$$\text{Weighted Sum} = (x_1 \cdot w_1) + (x_2 \cdot w_2) + (x_3 \cdot w_3)$$

To make a final decision, the perceptron compares this weighted sum against a threshold value. If the sum is greater than the threshold, the neuron fires (outputs 1). If it's less or equal, it stays silent (outputs 0).

In modern machine learning, we rearrange this threshold by introducing a variable called the **bias** ($b$), which is the negative threshold ($b = -\text{threshold}$). This simplifies our master equation to:

$$\text{Output} = \begin{cases} 1 & \text{if } \sum (x_i \cdot w_i) + b > 0 \\ 0 & \text{if } \sum (x_i \cdot w_i) + b \le 0 \end{cases}$$

> **Why Bias Matters:** Think of the bias as how easy it is to get the neuron to fire. If the bias is a large positive number, the neuron will fire very easily, even if the inputs are weak. If the bias is a large negative number, it takes a massive amount of positive input to get the neuron to fire.

By adjusting the weights and the bias, we change how the neuron responds to data. This adjustment process is exactly what we mean when we talk about a machine **"learning."**

--- 
## 2. Practical Application: Logic Gates (The AND Gate)

To understand how a single neuron processes information mechanically, we can configure a single perceptron to act as a logical **AND gate**.

An AND gate has two binary inputs ($x_1$ and $x_2$). It outputs a `1` *only* if both inputs are `1`. If either input is `0`, or if both are `0`, it outputs a `0`.

### Truth Table for an AND Gate
| Input $x_1$ | Input $x_2$ | Target Output |
| :---: | :---: | :---: |
| 0 | 0 | 0 |
| 0 | 1 | 0 |
| 1 | 0 | 0 |
| 1 | 1 | 1 |

### 🛠️ Configuring the Parameters
Let's look at how the inputs pass through the weights, sum up, combine with the bias ($b$), and pass through the activation threshold function.

![Single Perceptron](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSccSD5t2uHkZ_qhSgVtIN9-0eUTYLd3QsuSJn2CgLFjiNkMBEWplBdlB4&s=10)

Our net input equation is:
$$z = (x_1 \cdot w_1) + (x_2 \cdot w_2) + b$$

If $z > 0$, the activation function outputs `1`. If $z \le 0$, it outputs `0`.
We can manually set the parameters to the following values to achieve an AND gate configuration:
* $w_1 = 1.0$
* $w_2 = 1.0$
* $b = -1.5$

### Tracing the Mathematical Scenarios

* **Scenario A: $x_1 = 1, x_2 = 0$**
    $$z = (1 \cdot 1) + (0 \cdot 1) - 1.5 = -0.5$$
    Since $-0.5 \le 0$, the output is **0**. (Matches Truth Table)
    
* **Scenario B: $x_1 = 1, x_2 = 1$**
    $$z = (1 \cdot 1) + (1 \cdot 1) - 1.5 = 0.5$$
    Since $0.5 > 0$, the output is **1**. (Matches Truth Table)
    
* **Scenario C: $x_1 = 0, x_2 = 0$**
    $$z = (0 \cdot 1) + (0 \cdot 1) - 1.5 = -1.5$$
    Since $-1.5 \le 0$, the output is **0**. (Matches Truth Table)
    
* **Scenario D: $x_1 = 0, x_2 = 1$**
    $$z = (0 \cdot 1) + (1 \cdot 1) - 1.5 = -0.5$$
    Since $-0.5 \le 0$, the output is **0**. (Matches Truth Table)

--- 
## 3. Activation Functions: The Smooth Transition

In our rigid perceptron model, the output changes instantly from `0` to `1` the exact moment $z$ crosses `0`. This is known as a **Step Function**.

While excellent for binary logical evaluation, the step function is too rigid for complex systems. A tiny change in a weight might cause no change in the output at all, or it might flip the output completely. This makes it impossible for a deep network to make gradual, fine-tuned adjustments using calculus during learning.

To fix this, modern networks replace step functions with smooth, continuous curves called **Activation Functions**.

### 1. The Sigmoid Function
Instead of jumping abruptly, Sigmoid squashes any real-valued input $z$ into a smooth curve bounded between 0 and 1:
$$\sigma(z) = \frac{1}{1 + e^{-z}}$$

* If $z$ is a large positive number, the output is close to `1`.
* If $z$ is a large negative number, the output is close to `0`.
* If $z = 0$, the output is exactly `0.5`.

This output can be treated as a probability vector (e.g., "There is an 85% chance this image is a cat").

### 2. The ReLU Function (Rectified Linear Unit)
While Sigmoid is crucial for output layers and structures like LSTMs, ReLU is widely used in deep architectures like CNNs due to its extreme computational efficiency:
$$f(z) = \max(0, z)$$

* If $z$ is negative or zero, the output is strictly `0`.
* If $z$ is positive, the output scales linearly, matching $z$ itself.

### 3. The Tanh Function (Hyperbolic Tangent)
The Tanh function is a scaled and shifted version of the Sigmoid function. While Sigmoid squashes output between 0 and 1, Tanh maps input values to a range between **-1 and 1**.

$$\tanh(z) = \frac{e^z - e^{-z}}{e^z + e^{-z}}$$

* Zero-Centered Output: Because its output range is $[-1, 1]$, the average value of the outputs is closer to zero. This often helps the neural network converge faster during training because it keeps the data centered, reducing the likelihood of "zig-zagging" during gradient descent.
* Stronger Gradients: The gradient of Tanh is steeper than the gradient of Sigmoid, which can help alleviate some issues with slow learning, though it still suffers from the vanishing gradient problem at very high or very low input values.

> **Behavioral Comparison:** If we take the AND gate scenario where $x_1 = 1, x_2 = 0$ ($z = -0.5$):
> * The **Step Function** outputs `0`.
> * The **ReLU Function** clamps the negative value and outputs `0`.
> * The **Sigmoid Function** would yield $\sigma(-0.5) \approx 0.378$, transferring a non-zero signal forward.
> * The **Tanh Function** outputs $\tanh(-0.5) \approx -0.462$.

By allowing negative outputs, Tanh provides a more nuanced signal to the next layer, helping the network differentiate between "strongly off" (negative) and "weakly on" (positive) states.


![Avtivation Functions](https://studymachinelearning.com/wp-content/uploads/2019/10/summary_activation_fn.png)


--- 
## 4. The Core Limitation: The XOR Problem

In 1969, AI pioneers Marvin Minsky and Seymour Papert published proof that a single-layer perceptron fundamentally cannot learn an **XOR (Exclusive OR)** gate. This historic limitation led to the first "AI Winter."

### Truth Table for an XOR Gate
| Input $x_1$ | Input $x_2$ | Target Output |
| :---: | :---: | :---: |
| 0 | 0 | 0 |
| 0 | 1 | 1 |
| 1 | 0 | 1 |
| 1 | 1 | 0 |

### The Geometric View & Linear Separability
The input formula $w_1x_1 + w_2x_2 + b = 0$ represents a straight line on a 2D coordinate space. A single perceptron can only solve problems that are **linearly separable**—meaning you can draw a single straight line to isolate the `0` outputs from the `1` outputs.

```plaintext
AND Gate (Separable)            OR Gate (Separable)            XOR Gate (IMPOSSIBLE)
     x2                              x2                             x2
      |                               |                              |
    1 |  0       1                  1 |  1       1                 1 |  1       0
      |                               |                              |
    0 |  0       0                  0 |  0       1                 0 |  0       1
      +----------- x1                 +----------- x1                +----------- x1
         0       1                       0       1                      0       1
     (Line splits them)              (Line splits them)         (No straight line works!)
```

For the XOR gate, the `1` outputs reside at $(0,1)$ and $(1,0)$, while the `0` outputs reside at $(0,0)$ and $(1,1)$. It is geometrically impossible to divide these clusters using one straight line.

### The Solution: Multilayer Perceptrons (MLP)
To solve the XOR limitation, we combine multiple neurons by stacking them into layers. 

By taking inputs, passing them to an intermediate **Hidden Layer**, and routing those representations to an **Output Layer**, the network warps the coordinate space to establish non-linear decision boundaries. For example, one hidden neuron can map an OR space, another can map an AND space, and the output layer can subtract the metrics to solve XOR seamlessly. This layered structure marks the dawn of **Deep Learning**.

--- 
## 5. Python Sandbox Implementation

Below is a NumPy implementation of a single-layer perceptron utilizing the **Perceptron Learning Rule**. It starts with random weights and dynamically updates its parameters whenever it makes a classification error. The target is **AND Gate** (output is 1 only if both x and y is 1, 0 otherwise).

In [6]:
import numpy as np

class Perceptron:
    def __init__(self, input_size, learning_rate=0.1):
        # Initialize weights and bias to small random numbers or zeros
        self.weights = np.random.randn(input_size) * 0.01
        self.bias = 0.0
        self.lr = learning_rate
        
    def activation_function(self, z):
        # The rigid Step Function: 1 if z > 0, else 0
        return 1 if z > 0 else 0

    def forward(self, x):
        # Compute the weighted sum: z = (x1*w1 + x2*w2 + ...) + b
        z = np.dot(x, self.weights) + self.bias
        return self.activation_function(z)

    def train(self, X, y, epochs=10):
        print("Starting training...")
        print("X is:")
        print(X)
        print("The target is:")
        print(y)
        print("-" * 50)
        
        for epoch in range(epochs):
            total_errors = 0
            
            for idx, x_input in enumerate(X):
                target = y[idx]
                prediction = self.forward(x_input)
                
                # Calculate the error (Target - Prediction)
                error = target - prediction
                
                if error != 0:
                    total_errors += 1
                    # Perceptron Learning Rule updates:
                    # New Weight = Old Weight + (Learning Rate * Error * Input)
                    self.weights += self.lr * error * x_input
                    # New Bias = Old Bias + (Learning Rate * Error)
                    self.bias += self.lr * error
            
            print(f"Epoch {epoch+1}: Total classification errors = {total_errors}")
            print(f"Current Weights: {self.weights} | Bias: {self.bias}\n")
            
            # If the network makes zero mistakes, it has successfully learned!
            if total_errors == 0:
                print(f"🎉 Convergence reached early at epoch {epoch+1}!")
                break

# --- Execution Sandbox ---
if __name__ == "__main__":
    # 1. Define the inputs for the AND gate truth table
    X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])
    
    # 2. Define the target outputs for AND gate
    y = np.array([0, 0, 0, 1])
    
    # 3. Instantiate and train our single neuron
    np.random.seed(42) 
    nn = Perceptron(input_size=2, learning_rate=0.1)
    nn.train(X, y, epochs=20)
    
    # 4. Verify the final trained predictions
    print("\n" + "="*50)
    print("Final Trained Network Predictions:")
    print("="*50)
    for x_input in X:
        pred = nn.forward(x_input)
        print(f"Input: {x_input} ---> Predicted Output: {pred}")

Starting training...
X is:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
The target is:
[0 0 0 1]
--------------------------------------------------
Epoch 1: Total classification errors = 2
Current Weights: [0.00496714 0.09861736] | Bias: 0.0

Epoch 2: Total classification errors = 2
Current Weights: [0.10496714 0.09861736] | Bias: 0.0

Epoch 3: Total classification errors = 3
Current Weights: [0.10496714 0.09861736] | Bias: -0.1

Epoch 4: Total classification errors = 2
Current Weights: [0.10496714 0.19861736] | Bias: -0.1

Epoch 5: Total classification errors = 1
Current Weights: [0.10496714 0.09861736] | Bias: -0.2

Epoch 6: Total classification errors = 0
Current Weights: [0.10496714 0.09861736] | Bias: -0.2

🎉 Convergence reached early at epoch 6!

Final Trained Network Predictions:
Input: [0 0] ---> Predicted Output: 0
Input: [0 1] ---> Predicted Output: 0
Input: [1 0] ---> Predicted Output: 0
Input: [1 1] ---> Predicted Output: 1


Now, when tried to optmize the weights for target **XOR Gate** (1 if x $\neq$ y; 0 if x = y), the Perceptron fails to find the optimum weights and bias values. Below we run with 20 epochs. It will fail however, no matter the number of passes. 

In [7]:
# 1. The input the is the same
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# 2. Target outputs for XOR gate
y = np.array([0, 1, 1, 0])

# 3. Instantiate and train our single neuron
np.random.seed(42) 
nn = Perceptron(input_size=2, learning_rate=0.1)
nn.train(X, y, epochs=20)

# 4. Verify the final trained predictions
print("\n" + "="*50)
print("Final Trained Network Predictions:")
print("="*50)
for x_input in X:
    pred = nn.forward(x_input)
    print(f"Input: {x_input} ---> Predicted Output: {pred}")

Starting training...
X is:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
The target is:
[0 1 1 0]
--------------------------------------------------
Epoch 1: Total classification errors = 2
Current Weights: [-0.09503286 -0.00138264] | Bias: 0.0

Epoch 2: Total classification errors = 2
Current Weights: [-0.19503286 -0.00138264] | Bias: 0.0

Epoch 3: Total classification errors = 3
Current Weights: [-0.19503286 -0.00138264] | Bias: 0.1

Epoch 4: Total classification errors = 4
Current Weights: [-0.19503286 -0.00138264] | Bias: 0.1

Epoch 5: Total classification errors = 4
Current Weights: [-0.19503286 -0.00138264] | Bias: 0.1

Epoch 6: Total classification errors = 4
Current Weights: [-0.19503286 -0.00138264] | Bias: 0.1

Epoch 7: Total classification errors = 4
Current Weights: [-0.19503286 -0.00138264] | Bias: 0.1

Epoch 8: Total classification errors = 4
Current Weights: [-0.19503286 -0.00138264] | Bias: 0.1

Epoch 9: Total classification errors = 4
Current Weights: [-0.19503286 -0.00138264] | Bias: 

### Understanding the Mechanics
Inside the training loop, parameter updates are executed sequentially using the following mathematical adjustments whenever a prediction mismatch occurs:
$$\Delta w_i = \eta \cdot (\text{target} - \text{prediction}) \cdot x_i$$
$$\Delta b = \eta \cdot (\text{target} - \text{prediction})$$
*(where $\eta$ represents the learning rate).* 

If the target is `1` but the model predicts `0`, the error evaluates to $+1$. The weights scaling any active inputs ($x_i = 1$) scale upward, increasing the mathematical probability that the neuron fires next time it encounters this input vector. If the target is `0` but the model predicts `1`, the resulting negative error reduces both active weights and bias values to suppress execution.

--- 
## 6. Optimization Insights: Mechanics of Data Flow

An critical architectural observation of the implementation code above is its updating strategy: **When the network encounters an error at a given index, parameters change instantly in-flight.** Therefore, subsequent samples inside the same epoch are processed using the newly altered weights.

This behavior defines specific operational paradigms in deep learning. Below are the three primary methods used to handle dataset routing and weight optimization adjustments:

### 1. Online / Stochastic Learning (Used in the Script above)
* **Mechanism:** Parameter updates are calculated and applied immediately after analyzing every individual sample.
* **Pros:** Highly dynamic processing; fits easily within memory constraints because only single instances are parsed at a time.
* **Cons:** Weight adjustments are incredibly noisy and volatile, often creating a "tugging match" where updating parameters for one input inadvertently degrades performance for an alternate sample.

### 2. Batch Gradient Descent
* **Mechanism:** The network executes a complete forward pass through every sample in the dataset, evaluates the aggregate error mean, and performs exactly one parameter optimization step per epoch.
* **Pros:** Smooth, stable mathematical convergence pathways.
* **Cons:** Highly inefficient and memory-intensive for large datasets (e.g., millions of rows), requiring massive local hardware processing resources before making initial adjustments.

### 3. Mini-batch Gradient Descent (The Industry Standard)
* **Mechanism:** The dataset is divided into small, uniform subsets (e.g., configurations of 32, 64, or 256 samples). The system processes a mini-batch, averages its corresponding error matrix, updates the weight configurations, and cycles to the next batch.
* **Why It's Used:** It strikes a balanced trade-off. It provides the stability of batch processing while accelerating runtime performance by maximizing vector matrix multiplication on modern hardware architectures (GPUs).